name: Test

on:
  push:
    branches-ignore: [develop, master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 18.17.1
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Test
        run: npm run test:ci
